name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: "${{matrix.os}}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    env: 
      MONGODB_URL: ${{secrets.MONGODB_URL}}
      PORT: ${{secrets.PORT}}
      CLOUD_NAME: ${{secrets.CLOUD_NAME}}
      CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
      CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
      CC_TEST_REPORTER_ID: ${{secrets.CODECLIMATE_TEST_REPORTER_ID}}
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
  
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
    - name: Set Codecov status
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api "repos/${{ github.repository }}/check-runs" -H "Accept: application/vnd.github.v3+json" \
          -f name="codecov/patch" -f head_sha="${{ github.sha }}" -f status="completed" -f conclusion="success"
